# Generated by Django 5.1.3 on 2024-11-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_patient_name_patient_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donor",
            options={"verbose_name": "Donor", "verbose_name_plural": "Donors"},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "Patient", "verbose_name_plural": "Patients"},
        ),
    ]
