# Generated by Django 5.1.3 on 2024-11-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_patient_options_patient_reason_patient_status_and_more'),
        ('myapp', '0012_auto_20241125_2023'),
    ]

    operations = [
    ]
